### ISSUE TITLE
Ticket system misconfigured?

### ISSUE THREAD

**Issue by SaturnHafen** [hpi-schul-cloud/nuxt-client#2080]
Das Ticketsystem für Featurerequests scheint falsch eingestellt zu sein.

Wenn ich auf den folgenden Link klicke https://ticketsystem.schul-cloud.org/secure/CreateIssue!default.jspa (nicht eingeloggt) kommt der Fehler, der im Screenshot zu sehen ist. (Man kann sich auch nicht selbst einen Account erstellen)
![image](https://user-images.githubusercontent.com/37272151/158254874-92d8ef7f-c7e2-4c17-960e-a702bc41a108.png)
Der Link wird einem vorgeschlagen, wenn man einen neuen Issue erstellt.

Mein Feature-Request war auch ganz simpel: Innerhalb von Code-Blöcken sollte der Text nur an Wortgrenzen umgebrochen werden bzw. wenn es unbedingt im Wort sein muss, dann sollte kein `-` hinzugefügt werden, da ansonsten Schüler:innen, die den Text abtippen sich potenziell vertippen.

Liebe Grüße

**Comment by Loki-Afro** [comment]
@SaturnHafen your best chances for feature requests is probably currently within your school-cloud instance, in the help section and then feature request or wish, something like that.

due to organizational reasons we use jira as our bug tracking systems, which is not public.

although i relayed your wish/feature request, you probably won't get any notification on that.

==
other than that .. a new editor or rather major update of an editor is currently implemented https://github.com/hpi-schul-cloud/ckeditor

not an expert on that topic, but maybe its the underlying editor that causes this behavior

==
feel free to reopen that issue
